<?php
    //print_r($schoolData);
    $years=array();
    for($i=date('Y')+1;$i>(date('Y')-5);$i--){
        $years[$i]=$i+543;
    }
    helper('form');
    $data=array(array(
        'label'=>'ชื่อสถานประกอบการ',
        'type'=>'text',
        'id'=>'business_id',
        'def'=>'',
         ),         
         array(
            'label'=>'ชื่อหลักสูตรที่พัฒนา',
            'type'=>'text',
            'id'=>'curriculum_name',
            'def'=>'',
            'required'=>true,
             ),      
         array(
            'label'=>'ปีที่พัฒนาหลักสูตร',
            'type'=>'select',
            'id'=>'curriculum_year',
            'items'=>$years,
            'def'=>date('Y'),
            'required'=>true,
             ),       
         array(
            'label'=>'การพัฒนา Skill Gap ตอบสนองภาคการผลิตและบริการใน 10 กลุ่มอุตสาหกรรมหลัก',
            'type'=>'check_group',
            'id'=>'skill_gap',
            'def'=>'',
            'items'=>array(
                'skill_01'=>array(
                    'text'=>'ยานยนต์สมัยใหม่',
                    'value'=>'Y',
                    'checked'=>false,
                    ),
                
                'skill_02'=>array(
                    'text'=>'อิเล็กทรอนิกส์อัฉริยะ',
                    'value'=>'Y',
                    'checked'=>false,
                    ),                
                'skill_03'=>array(
                    'text'=>'ท่องเที่ยวรายได้ดี',
                    'value'=>'Y',
                    'checked'=>false,
                    ),                
                'skill_04'=>array(
                    'text'=>'เกษตรและเทคโนโลยีชีวภาพ',
                    'value'=>'Y',
                    'checked'=>false,
                    ),               
                'skill_05'=>array(
                    'text'=>'แปรรูปอาหาร',
                    'value'=>'Y',
                    'checked'=>false,
                    ),          
                'skill_06'=>array(
                    'text'=>'หุ่นยนต์',
                    'value'=>'Y',
                    'checked'=>false,
                    ),          
                'skill_07'=>array(
                    'text'=>'การบินและโลจิสติกส์',
                    'value'=>'Y',
                    'checked'=>false,
                    ),          
                'skill_08'=>array(
                    'text'=>'เชื้อเพลิงเคมีชีวภาพ',
                    'value'=>'Y',
                    'checked'=>false,
                    ),          
                'skill_09'=>array(
                    'text'=>'ดิจิตอล',
                    'value'=>'Y',
                    'checked'=>false,
                    ),          
                'skill_10'=>array(
                    'text'=>'การแพทย์ครบวงจร',
                    'value'=>'Y',
                    'checked'=>false,
                    ),
                ),
            ),
         array(
             'label'=>'ระดับของหลักสูตร',
             'type'=>'check_group',
             'id'=>'spupport_edu',
             'items'=>array(
                 'support_vc_edu'=>array('text'=>'ปวช.',
                                         'value'=>'Y',
                                         'checked'=>isset($mou_data)?$mou_data->support_vc_edu=='Y'?true:false:false,
                                         ),
                 'support_hvc_edu'=>array('text'=>'ปวส.',
                                         'value'=>'Y',
                                         'checked'=>isset($mou_data)?$mou_data->support_hvc_edu=='Y'?true:false:false,
                                         ),
                 'support_btech_edu'=>array('text'=>'ทล.บ.',
                                         'value'=>'Y',
                                         'checked'=>isset($mou_data)?$mou_data->support_btech_edu=='Y'?true:false:false,
                                         ),
                 'support_short_course'=>array('text'=>'ระยะสั้น',
                                         'value'=>'Y',
                                         'checked'=>isset($mou_data)?$mou_data->support_short_course=='Y'?true:false:false,
                                         ),
                 'support_no_specific'=>array('text'=>'อื่นๆ',
                                         'value'=>'Y',
                                         'checked'=>isset($mou_data)?$mou_data->support_no_specific=='Y'?true:false:false,
                                         ),
             ),
             'required'=>true,
         ),
         array(
            'label'=>'สาขาวิชา',
            'type'=>'text',
            'id'=>'majors',
            'placeholder'=>'เช่น ช่างไฟฟ้ากำลัง,ช่างอิเล็กทรอนิกส์ โดยขั้นแต่ละสาขาด้วยเครื่องหมายจุลภาค (,)',
            'def'=>'',
             ),
         array(
            'label'=>'จำนวนชั่วโมงการอบรม',
            'type'=>'number',
            'id'=>'curriculumHour',
            'placeholder'=>'ระบุจำนวนชั่วโมงที่ใช้ในการอบรม',
            'def'=>'',
             ),
         array(
            'label'=>'เป้าหมายการอบรม',
            'type'=>'number',
            'id'=>'curriculum_target',
            'placeholder'=>'ระบุจำนวนผู้เข้าอบรมที่คาดหวัง',
            'def'=>'',
             ),
         array(
            'label'=>'การดำเนินการของสถานประกอบการ',
            'type'=>'textarea',
            'id'=>'business_action',
            'placeholder'=>'เช่น
1) จัดหาบุคลากรที่เชียวชาญมาอบรมให้
2) นำผู้เรียนเข้ารับการอบรมในสถานประกอบการ
3) มอบวัสดุแบะอุปกรณ์ในการฝึกอบรม',
            'def'=>'',
             ),
         array(
            'label'=>'ไฟล์หลักสูตร สแกนเอกสารหลักสูตรเป็นไฟล์ PDF',
            'type'=>'file',
            'id'=>'attach_file',
            'def'=>'',
             ),
         array(
            'label'=>'ภาพถ่ายขณะพัฒนาหลักสูตร',
            'type'=>'file',
            'id'=>'pictures',
            'def'=>'',
             ),
         array(
            'label'=>'จำนวนผู้เข้ารับอบรม',
            'type'=>'number',
            'id'=>'training_amount',
            'def'=>'',
             ),
         array(
            'label'=>'ภาพถ่ายขณะจัดการอบรม',
            'type'=>'file',
            'id'=>'training_pictures',
            'def'=>'',
             ),
         array(
             'label'=>'บันทึกข้อมูล',
             'type'=>'submit',
         ),
    );

    $form=array(
        'formName'=>'ข้อมูลหลักสูตร',
        'inputs'=>$data,
        'action'=>site_url('public/gov/saveCurriculum'),
        'method'=>'post',
        'enctype'=>'multipart/form-data',
    );
    
    print genForm($form);