<?php
helper('form');
helper('user');
//print_r($mou_data);
$data=array(array(
                    'label'=>'ชื่อสถานประกอบการ',
                    'type'=>'text',
                    'id'=>'business_name',
                    'def'=>$business_data->business_name,
                    'disabled'=>true,
                ),
                array(
                    'type'=>'hidden',
                    'id'=>'mou_id',
                    'def'=>$mou_data->mou_id,
                ),
                array(
                    'type'=>'hidden',
                    'id'=>'business_id',
                    'def'=>$business_data->business_id,
                ),
                array(
                    'type'=>'hidden',
                    'id'=>'org_id',
                    'def'=>current_user('org_code'),
                ),
                array(
                    'label'=>'ที่อยู่',
                    'type'=>'text',
                    'id'=>'address',
                    'def'=>'เลขที่ '.($business_data->address_no!=''?$business_data->address_no:'-').' ถนน'.($business_data->road!=''?$business_data->road:'-').' ตำบล'.$subdistrict[$business_data->subdistrict_id].' อำเภอ'.$district[$business_data->district_id].'จังหวัด'.$province[$business_data->province_id],
                    'disabled'=>true,
                ),
                array(
                    'label'=>'ระดับของความร่วมมือ',
                    'type'=>'select',
                    'id'=>'level',
                    'items'=>array(
                        'level_1'=>'ระดับ 1 : เกี่ยวกับ CSR การฝึกงาน กิจกรรมเฉพาะกิจ (รวมระยะสั้น)',
                        'level_2'=>'ระดับ 2 : เกี่ยวกับ CSR การฝึกงาน กิจกรรมเฉพาะกิจ (รวมระยะสั้น) และการจัดการเรียนการสอนทวิภาคี',
                        'level_3'=>'ระดับ 3 : เกี่ยวกับ CSR การฝึกงาน กิจกรรมเฉพาะกิจ (รวมระยะสั้น) และการจัดการเรียนการสอนทวิภาคี และมีการร่วมลงทุนระหว่างสถานประกอบการและสถานศึกษา',
                    ),
                    'def'=>$mou_data->level,
                    'required'=>true,
                ),                
                array(
                    'label'=>'ระดับการศึกษาที่ร่วมมือ',
                    'type'=>'check_group',
                    'id'=>'spupport_edu',
                    'items'=>array(
                        'support_vc_edu'=>array('text'=>'ปวช.',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_vc_edu=='Y'?true:false,
                                                ),
                        'support_hvc_edu'=>array('text'=>'ปวส.',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_hvc_edu=='Y'?true:false,
                                                ),
                        'support_btech_edu'=>array('text'=>'ทล.บ.',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_btech_edu=='Y'?true:false,
                                                ),
                        'support_short_course'=>array('text'=>'ระยะสั้น',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_short_course=='Y'?true:false,
                                                ),
                        'support_no_specific'=>array('text'=>'อื่นๆ',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_no_specific=='Y'?true:false,
                                                ),
                    ),
                    'required'=>true,
                ),
                array(
                    'label'=>'สาขาวิชาที่ลงนาม',
                    'type'=>'text',
                    'id'=>'major',
                    'def'=>$mou_data->major,
                    'required'=>false,
                ),
                array(
                    'label'=>'เป้าหมายการรับนักศึกษาฝึกงาน/ฝึกอาชีพ (ระบุจำนวนคนรวมทุกสาขา)',
                    'type'=>'number',
                    'id'=>'dve_target',
                    'def'=>$mou_data->dve_target,
                    'required'=>true,
                ),
                array(
                    'label'=>'รูปแบบการจัดการศึกษา',
                    'type'=>'check_group',
                    'id'=>'dve',
                    'items'=>array(
                        'support_normal'=>array('text'=>'ระบบปกติ',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_normal=='Y'?true:false,
                                                ),
                        'support_dve'=>array('text'=>'ระบบทวิภาคี',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_dve=='Y'?true:false,
                                                ),
                                            ),
                    'required'=>true,
                ),
                array(
                    'label'=>'การฝึกงานในประเทศ/ต่างประเทศ',
                    'type'=>'check_group',
                    'id'=>'oversea',
                    'items'=>array(
                        'support_local_training'=>array('text'=>'มีการฝึกงานในประเทศ',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_local_training=='Y'?true:false,
                                                ),
                        'support_oversea_training'=>array('text'=>'มีการฝึกงานในต่างประเทศ',
                                                'value'=>'Y',
                                                'checked'=>$mou_data->support_oversea_training=='Y'?true:false,
                                                ),
                                            ),
                    'required'=>true,
                ),
                array(
                    'label'=>'ชื่อผู้บริหารภาครัฐที่ลงนาม',
                    'type'=>'text',
                    'id'=>'govSignName',
                    'def'=>$mou_data->director_name,
                    'required'=>true,
                ),
                array(
                    'label'=>'ตำแหน่งผู้บริหารภาครัฐ',
                    'type'=>'text',
                    'id'=>'govSignNamePosition',
                    'def'=>$mou_data->director_type,
                    'required'=>true,
                ),
                array(
                    'label'=>'ชื่อผู้บริหารสถานประกอบการ/ตัวแทนที่ลงนาม',
                    'type'=>'text',
                    'id'=>'businessSignName',
                    'def'=>$mou_data->ceo_name,
                    'required'=>true,
                ),
                array(
                    'label'=>'ตำแหน่งผู้บริหารสถานประกอบการ/ตัวแทน',
                    'type'=>'text',
                    'id'=>'businessSignNamePosition',
                    'def'=>$mou_data->ceo_type,
                    'required'=>true,
                ),
                array(
                    'label'=>'วันที่ลงนามความร่วมมือ',
                    'type'=>'date',
                    'id'=>'mou_date',
                    'def'=>$mou_data->mou_date?$mou_data->mou_date:date('Y-m-d'),
                    'max'=>date(('Y-m-d'),strtotime(' + 365 day')),
                    'min'=>date(('Y-m-d'),strtotime(' - 100 year')),
                    'required'=>true,
                ),
                array(
                    'label'=>'วันที่เริ่มความร่วมมือ',
                    'type'=>'date',
                    'id'=>'mou_start_date',
                    'def'=>$mou_data->mou_start_date?$mou_data->mou_start_date:date('Y-m-d'),
                    'max'=>date(('Y-m-d'),strtotime(' + 365 day')),
                    'min'=>date(('Y-m-d'),strtotime(' - 100 year')),
                    'required'=>true,
                ),
                array(
                    'label'=>'วันที่สิ้นสุดความร่วมมือ',
                    'type'=>'date',
                    'id'=>'mou_end_date',
                    'def'=>$mou_data->mou_end_date?$mou_data->mou_end_date:date('Y-m-d',strtotime(' + 3 year')),
                    'max'=>date(('Y-m-d'),strtotime(' + 10 year')),
                    'min'=>date(('Y-m-d'),strtotime(' - 100 year')),
                    'required'=>true,
                ),
                array(
                    'label'=>'สถานที่ลงนาม',
                    'type'=>'text',
                    'id'=>'mou_sign_place',
                    'def'=>$mou_data->mou_sign_place,
                    'required'=>true,
                ),
                array(
                    'label'=>'วัตถุประสงค์ในการทำ MOU',
                    'type'=>'text',
                    'id'=>'object',
                    'def'=>$mou_data->object,
                    'required'=>true,
                ),
                array(
                    'label'=>'ค่าตอบแทนการฝึกงาน/ฝึกอาชีพโดยประมาณ',
                    'type'=>'select',
                    'id'=>'wage',
                    'items'=>array(
                        '0'=>'1. ไม่ให้ค่าตอบแทนเป็นเงิน',
                        '1'=>'2. ต่ำกว่า 150 บาท/วัน',
                        '2'=>'3. 150 - 300 บาท/วัน',
                        '3'=>'4. มากกว่า 300 บาท/วัน',
                        '4'=>'5. น้อยกว่า 6,000 บาท/เดือน',
                        '5'=>'6. 6,000 - 10,000 บาท/เดือน',
                        '6'=>'7. มากกว่า 10,000 บาท/เดือน',
                    ),
                    'def'=>$mou_data->wage,
                    'required'=>true,
                ),
                array(
                    'label'=>'สิทธิประโยชน์อื่นนอกจากค่าตอบแทน',
                    'type'=>'text',
                    'id'=>'benefits',
                    'def'=>$mou_data->benefits,
                    'required'=>false,
                ),array(
                    'label'=>'ข้อผูกมัด,พันธผูกพันกับผู้เรียน',
                    'type'=>'text',
                    'id'=>'obligation',
                    'def'=>$mou_data->obligation,
                    'required'=>false,
                ),
                array(
                    'label'=>'ไฟล์ MOU (.PDF)',
                    'type'=>'file',
                    'id'=>'mou',
                    'accept'=>'application/pdf',
                    'required'=>false,
                    'multiple'=>true,
                ),
                array(
                    'label'=>'ภาพถ่ายขณะลงนาม (.JPG)',
                    'type'=>'file',
                    'id'=>'mou',
                    'accept'=>'image/gif, image/jpeg, image/png',
                    'required'=>false,
                    'multiple'=>true,
                ),
            array(
                'label'=>'บันทึกข้อมูล',
                'type'=>'submit',
            ),
        );
$form=array(
    'formName'=>'ข้อมูลการทำความร่วมมือ',
    'inputs'=>$data,
    'action'=>site_url('public/mou/save'),
    'method'=>'post',
    'enctype'=>'multipart/form-data',
);

print genForm($form);
?>