<?php
helper('form');
helper('user');
//print_r($business_data);
$data=array(array(
                    'label'=>'ชื่อสถานประกอบการ',
                    'type'=>'text',
                    'id'=>'business_name',
                    'def'=>$business_data->business_name,
                    'disabled'=>true,
                ),
                array(
                    'type'=>'hidden',
                    'id'=>'business_id',
                    'def'=>$business_data->business_id,
                ),
                array(
                    'type'=>'hidden',
                    'id'=>'org_id',
                    'def'=>current_user('org_code'),
                ),
                array(
                    'label'=>'ที่อยู่',
                    'type'=>'text',
                    'id'=>'address',
                    'def'=>'เลขที่ '.($business_data->address_no!=''?$business_data->address_no:'-').' ถนน'.($business_data->road!=''?$business_data->road:'-').' ตำบล'.$subdistrict[$business_data->subdistrict_id].' อำเภอ'.$district[$business_data->district_id].'จังหวัด'.$province[$business_data->province_id],
                    'disabled'=>true,
                ),
                array(
                    'label'=>'ระดับของความร่วมมือ',
                    'type'=>'select',
                    'id'=>'level',
                    'items'=>array(
                        'level_1'=>'ระดับ 1 : เกี่ยวกับ CSR การฝึกงาน กิจกรรมเฉพาะกิจ (รวมระยะสั้น)',
                        'level_2'=>'ระดับ 2 : เกี่ยวกับ CSR การฝึกงาน กิจกรรมเฉพาะกิจ (รวมระยะสั้น) และการจัดการเรียนการสอนทวิภาคี',
                        'level_3'=>'ระดับ 3 : เกี่ยวกับ CSR การฝึกงาน กิจกรรมเฉพาะกิจ (รวมระยะสั้น) และการจัดการเรียนการสอนทวิภาคี และมีการร่วมลงทุนระหว่างสถานประกอบการและสถานศึกษา',
                    ),
                    'required'=>true,
                ),                
                array(
                    'label'=>'ระดับการศึกษาที่ร่วมมือ',
                    'type'=>'check_group',
                    'id'=>'spupport_edu',
                    'items'=>array(
                        'support_vc_edu'=>array('text'=>'ปวช.',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                        'support_hvc_edu'=>array('text'=>'ปวส.',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                        'support_btech_edu'=>array('text'=>'ทล.บ.',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                        'support_short_coruse'=>array('text'=>'ระยะสั้น',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                        'support_other_edu'=>array('text'=>'อื่นๆ',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                    ),
                    'required'=>true,
                ),
                array(
                    'label'=>'สาขาวิชาที่ลงนาม',
                    'type'=>'text',
                    'id'=>'major',
                    'required'=>false,
                ),
                array(
                    'label'=>'เป้าหมายการรับนักศึกษาฝึกงาน/ฝึกอาชีพ (ระบุจำนวนคนรวมทุกสาขา)',
                    'type'=>'number',
                    'id'=>'dve_target',
                    'def'=>0,
                    'required'=>true,
                ),
                array(
                    'label'=>'รูปแบบการจัดการศึกษา',
                    'type'=>'check_group',
                    'id'=>'dve',
                    'items'=>array(
                        'support_normal'=>array('text'=>'ระบบปกติ',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                        'support_dve'=>array('text'=>'ระบบทวิภาคี',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                                            ),
                    'required'=>true,
                ),
                array(
                    'label'=>'การฝึกงานในประเทศ/ต่างประเทศ',
                    'type'=>'check_group',
                    'id'=>'oversea',
                    'items'=>array(
                        'support_local_training'=>array('text'=>'มีการฝึกงานในประเทศ',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                        'support_oversea_training'=>array('text'=>'มีการฝึกงานในต่างประเทศ',
                                                'value'=>'Y',
                                                'checked'=>false,
                                                ),
                                            ),
                    'required'=>true,
                ),
                array(
                    'label'=>'ชื่อผู้บริหารภาครัฐที่ลงนาม',
                    'type'=>'text',
                    'id'=>'govSignName',
                    'required'=>true,
                ),
                array(
                    'label'=>'ตำแหน่งผู้บริหารภาครัฐ',
                    'type'=>'text',
                    'id'=>'govSignNamePosition',
                    'required'=>true,
                ),
                array(
                    'label'=>'ชื่อผู้บริหารสถานประกอบการ/ตัวแทนที่ลงนาม',
                    'type'=>'text',
                    'id'=>'businessSignName',
                    'required'=>true,
                ),
                array(
                    'label'=>'ตำแหน่งผู้บริหารสถานประกอบการ/ตัวแทน',
                    'type'=>'text',
                    'id'=>'businessSignNamePosition',
                    'required'=>true,
                ),
                array(
                    'label'=>'วันที่ลงนามความร่วมมือ',
                    'type'=>'date',
                    'id'=>'mou_date',
                    'def'=>date('Y-m-d'),
                    'max'=>date(('Y-m-d'),strtotime(' + 365 day')),
                    'min'=>date(('Y-m-d'),strtotime(' - 100 year')),
                    'required'=>true,
                ),
                array(
                    'label'=>'วันที่เริ่มความร่วมมือ',
                    'type'=>'date',
                    'id'=>'mou_start_date',
                    'def'=>date('Y-m-d'),
                    'max'=>date(('Y-m-d'),strtotime(' + 365 day')),
                    'min'=>date(('Y-m-d'),strtotime(' - 100 year')),
                    'required'=>true,
                ),
                array(
                    'label'=>'วันที่สิ้นสุดความร่วมมือ',
                    'type'=>'date',
                    'id'=>'mou_end_date',
                    'def'=>date('Y-m-d',strtotime(' + 3 year')),
                    'max'=>date(('Y-m-d'),strtotime(' + 10 year')),
                    'min'=>date(('Y-m-d'),strtotime(' - 100 year')),
                    'required'=>true,
                ),
                array(
                    'label'=>'สถานที่ลงนาม',
                    'type'=>'text',
                    'id'=>'mou_sign_place',
                    'required'=>true,
                ),
                array(
                    'label'=>'วัตถุประสงค์ในการทำ MOU',
                    'type'=>'text',
                    'id'=>'object',
                    'required'=>true,
                ),
                array(
                    'label'=>'ค่าตอบแทนการฝึกงาน/ฝึกอาชีพโดยประมาณ',
                    'type'=>'select',
                    'id'=>'wage',
                    'items'=>array(
                        '0'=>'1. ไม่ให้ค่าตอบแทนเป็นเงิน',
                        '1'=>'2. ต่ำกว่า 150 บาท/วัน',
                        '2'=>'3. 150 - 300 บาท/วัน',
                        '3'=>'4. มากกว่า 300 บาท/วัน',
                        '4'=>'5. น้อยกว่า 6,000 บาท/เดือน',
                        '5'=>'6. 6,000 - 10,000 บาท/เดือน',
                        '6'=>'7. มากกว่า 10,000 บาท/เดือน',
                    ),
                    'required'=>true,
                ),
                array(
                    'label'=>'สิทธิประโยชน์อื่นนอกจากค่าตอบแทน',
                    'type'=>'text',
                    'id'=>'benefits',
                    'required'=>false,
                ),array(
                    'label'=>'ข้อผูกมัด,พันธผูกพันกับผู้เรียน',
                    'type'=>'text',
                    'id'=>'obligation',
                    'required'=>false,
                ),
                array(
                    'label'=>'ไฟล์ MOU',
                    'type'=>'file',
                    'id'=>'mou',
                    'accept'=>'.pdf,.PDF',
                    'required'=>false,
                ),
                array(
                    'label'=>'ภาพถ่ายขณะลงนาม',
                    'type'=>'file',
                    'id'=>'mou',
                    'accept'=>'.jpg,.JPG',
                    'required'=>false,
                ),
            array(
                'label'=>'บันทึกข้อมูล',
                'type'=>'submit',
            ),
        );
$form=array(
    'formName'=>'ข้อมูลการทำความร่วมมือ',
    'inputs'=>$data,
    'action'=>site_url('public/mou/save'),
    'method'=>'post',
);

print genForm($form);
?>